argocd-apps:
  applications:
    - name: nginx
      namespace: nginx
      project: default
      source:
        repoURL: https://github.com/Hamidzak/k8s-apps.git
        path: nginx
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: nginx
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
