argocd-apps:
  applications:
    - name: nginx-app
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/Hamidzak/k8s-apps.git
        targetRevision: main
        path: argocd/app-of-apps/nginx
      destination:
        server: https://kubernetes.default.svc
        namespace: nginx
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
